server:
  port: ${http.localhost.port.dataparser_port}

spring:
  profiles:
    active:
      - config-url-base
      - config-url-integration
  datasource:
    driver-class-name: MongoDB
    url: jdbc:mongodb://localhost:27017/tradingagent
  jpa:
    hibernate:
      ddl-auto: create-drop